### ISSUE TITLE
Using the paste function to make paths

### ISSUE THREAD

**Issue by dnieuw** [karlbrand/MolMedBasicRcourse#3]
In my experience, it is very confusing to many people why we use paste. I think we should remove it or give a clear example why and when you use paste to create (many) paths to load multiple files for instance.

**Comment by karlbrand** [comment]
I only discovered this comment now :$ cheers David. Ibelieve this was addressed, but will double check before closing (or you tell me otherwise).

**Comment by karlbrand** [comment]
Fixed (thank you Elizabeth!)
