### ISSUE TITLE
ggplot practical code missing

### ISSUE THREAD

**Issue by elizabethribble** [karlbrand/MolMedBasicRcourse#8]
David will you please add your ggplot practical code to the repository? We need to fix the issue of the duplicate column names in the solution to the problem where you use the aggregate function. I think once that is updated we are all set to create the full course reader.

**Comment by dnieuw** [comment]
I've properly separated the R and Rmd files for the ggplot chapter. Also the practical part and the lecture part are now properly separated.
The PDF in the lecture folder is old, needs to be regenerated.
